################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: > 
                    Leading financial institutions and technology providers use AllData Aggregation to gather financial data for millions of consumers, from more than 18,000 distinct data sources, including bank accounts, liability accounts including credit cards, investment and retirement accounts, as well as insurance and billers. </br></br>

                    Fiserv has been in the data aggregation business for more than 20 years. Thousands of businesses and millions of consumers trust Fiserv to help them maximize the power of data aggregation by easily integrating the data they need with any new or existing application, regardless of the underlying technology platform.
  whoIsItFor: Our AllData Aggregation products and services cater to financial institutions and fintechs to facilitate consumer-permissioned account connectivity.
featuredFeatures:
  - title: Account Verification
    description: >
      AllData® Aggregation makes setting up ACH Payments easier for senders. 
      A user provides their credentials, and AllData® Aggregation retrieves their accounts and routing numbers.
    tags: []
    bullets: []
    #links: ["docs/Online-Mobile-Digital/Wallets-AltPayments/Apple-Pay/Apple-Pay.md"]
    relatedDocs:
      - relatedDoc: 
        title: Common Use Cases
        description: >
          This document covers common use cases within the AllData Aggregation product, including a number of API Solutions.
        link: "/docs/alldata-common-use-cases.md"
      - relatedDoc: 
        title: APIs and Add Account Widget 
        description: >
          This document addresses how to Use AllData APIs and the Add Account Widget for multiple use cases.
        link: "/docs/add-account.md"
      - relatedDoc: 
        title: Widget Integration Guide
        description: >
          This document covers ways to speed implementation by leveraging AllData widgets.
        link: "/docs/alldata-next-gen.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: >
          This API is used to sign on to the AllData service. It authenticates the user and generates a session token.
          The session token can be used for subsequent calls and this token will expire after 18 minutes of ideal time.
          This session token is also required to launch the Add Account widget flow.
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: >
          This API can be used to fetch detail information about one or more FI login accounts of a user. It can be used to retrieve information about one or more login accounts.
          If no ID is specified, it returns information about all of user’s FI login accounts.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: This API is used to fetch the transactions for a banking account. It returns the transactions for the specified date range.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
  - title: Money Movement
    description: >
      Through AllData® Aggregation, accessing financial data needed for credit decisions happens quickly, eliminating the traditional paper chase. 
      AllData® Aggregation also streamlines the process for the borrower.
    tags: []
    bullets: []
    #links: ["docs/Resources/API-Documents/Use-Our-APIs.md"]
    relatedDocs:
      - relatedDoc: 
        title: Common Use Cases
        description: >
          This document covers common use cases within the AllData Aggregation product, including a number of API Solutions.
        link: "/docs/alldata-common-use-cases.md"
      - relatedDoc: 
        title: APIs and Add Account Widget 
        description: >
          This document addresses how to Use AllData APIs and the Add Account Widget for multiple use cases.
        link: "/docs/add-account.md"
      - relatedDoc: 
        title: Widget Integration Guide
        description: >
          This document covers ways to speed implementation by leveraging AllData widgets.
        link: "/docs/alldata-next-gen.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: >
          This API is used to sign on to the AllData service. It authenticates the user and generates a session token.
          The session token can be used for subsequent calls and this token will expire after 18 minutes of ideal time.
          This session token is also required to launch the Add Account widget flow.
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: >
          This API can be used to fetch detail information about one or more FI login accounts of a user. It can be used to retrieve information about one or more login accounts.
          If no ID is specified, it returns information about all of user’s FI login accounts.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: This API is used to fetch the transactions for a banking account. It returns the transactions for the specified date range.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
  - title: Lending & Account Opening
    description: > 
      AllData® Aggregation is used by businesses to provide consumers with a comprehensive view of their finances, for advisors to provide deeper 
      insight and better analysis, and for fintechs to develop innovative products and services.
    tags: []
    bullets: []
    relatedDocs:
      - relatedDoc: 
        title: Common Use Cases
        description: >
          This document covers common use cases within the AllData Aggregation product, including a number of API Solutions.
        link: "/docs/alldata-common-use-cases.md"
      - relatedDoc: 
        title: APIs and Add Account Widget 
        description: >
          This document addresses how to Use AllData APIs and the Add Account Widget for multiple use cases.
        link: "/docs/add-account.md"
      - relatedDoc: 
        title: Widget Integration Guide
        description: >
          This document covers ways to speed implementation by leveraging AllData widgets.
        link: "/docs/alldata-next-gen.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: >
          This API is used to sign on to the AllData service. It authenticates the user and generates a session token.
          The session token can be used for subsequent calls and this token will expire after 18 minutes of ideal time.
          This session token is also required to launch the Add Account widget flow.
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: >
          This API can be used to fetch detail information about one or more FI login accounts of a user. It can be used to retrieve information about one or more login accounts.
          If no ID is specified, it returns information about all of user’s FI login accounts.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: This API is used to fetch the transactions for a banking account. It returns the transactions for the specified date range.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
