################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: > 
                    Leading financial institutions and technology providers use AllData Aggregation to gather financial data for millions of consumers, from more than 18,000 distinct data sources, including bank accounts, liability accounts including credit cards, investment and retirement accounts, as well as insurance and billers. </br></br>

                    Fiserv has been in the data aggregation business for more than 20 years. Thousands of businesses and millions of consumers trust Fiserv to help them maximize the power of data aggregation by easily integrating the data they need with any new or existing application, regardless of the underlying technology platform.
  whoIsItFor: Testing...
featuredFeatures:
  - title: Account Verification
    description: >
      AllData Aggregation from Fiserv makes setting up ACH payments easier for senders. A user provides
      their credentials, and AllData Aggregation® retrieves their account and routing numbers. This
      not only simplifies the entire process, it also verifies the account provided is owned by the
      same person trying to initiate the ACH transfer.
    tags: []
    bullets: []
    #links: ["docs/Online-Mobile-Digital/Wallets-AltPayments/Apple-Pay/Apple-Pay.md"]
    relatedDocs:
      - relatedDoc: 
        title: Common Data Aggregation Use Cases and AllData API Solutions 
        link: "/docs/alldata-common-use-cases.md"
      - relatedDoc: 
        title: How to Use AllData APIs and Add Account Widget for Various Use Cases
      - relatedDoc: 
        title: Next-Gen Widgets Integration Guide
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
  - title: Money Movement
    description: >
      Through AllData® Aggregation, that all changes. Accessing financial data needed for credit decisions
      happens quickly, eliminating the traditional paper chase. AllData Aggregation also streamlines
      the process for the borrower. Rather than gathering documents and downloaded pdf’s from multiple sources.
    tags: []
    bullets: []
    #links: ["docs/Resources/API-Documents/Use-Our-APIs.md"]
    relatedDocs:
      - relatedDoc: 
        title: Getting Started 
        description: Commerce Hub allows developers to quickly enable secure and convenient Apple Pay payments in their app or website.
        link: "/docs/Getting-Started/Getting-Started-UCOM.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
  - title: Lending & Account Opening
    description: > 
      AllData Aggregation from Fiserv is used by businesses to provide consumers with a comprehensive view
      of their finances, for advisors to provide deeper insight and better analysis, and for fintechs to
      develop innovative products and services with speed and agility.
    tags: []
    bullets: []
    relatedDocs:
      - relatedDoc: 
        title: Getting Started 
        description: Point-of-Sale (POS) is the point at which a product is paid for. In-person transactions are conducted by a terminal or software. Online transactions are conducted by a software on their online store or mobile app.
        link: "/docs/Getting-Started/Getting-Started-InPerson.md"
      - relatedDoc: 
        title: EMV 
        description: Fiserv offers the industry's most complete, comprehensive and integrated EMV solution.
        link: "/docs/In-Person/Encrypted-Payments/EMV.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: Description here
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
